import { StyleSheet, Platform, Dimensions } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FCF2E9',
      
      // paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    tabContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 10,
    },
    tabButton: {
      paddingVertical: 8,
      paddingHorizontal: 20,
      borderBottomWidth: 2,
      borderBottomColor: '#00000000',
    },
    activeTab: {
      borderBottomColor: '#BE3E28',
    },
    tabText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
    },
    scrollView: {
      flex: 1,
    },
    
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderBottomWidth: 0,
      borderBottomColor: '#00000000',
    },
    backButton: {
      marginRight: 16,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#333',
    },
    clothesTitle: {
      color: '#BE3E28',
      fontSize: 28,
    },
    formSection: {
      padding: 18,
      marginBottom: 1,
      backgroundColor: '#FCF2E9',
      borderRadius: 10,
      marginHorizontal: 0,
      marginTop: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 12,
      color: '#333',
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold',
      marginBottom: 8,
      color: '#333',
    },
    input: {
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      padding: 12,
      marginBottom: 16,
      fontSize: 16,
    },
    textArea: {
      height: 100,
      textAlignVertical: 'top',
    },
    pickerContainer: {
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      marginBottom: 16,
      overflow: 'hidden',
      paddingHorizontal: 8,
    },
    picker: {
      height: 60,
      width: '100%',
    },
    helperText: {
      fontSize: 14,
      color: '#777',
      marginBottom: 16,
    },
    imagePickerButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    imageButton: {
      backgroundColor: '#fff',
      borderRadius: 10,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 0.48,
      flexDirection: 'row',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: '#E8A87C',
      height: 100,
      gap: 8,
    },
    galleryButton: {
      backgroundColor: '#fff',
      borderRadius: 10,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 0.48,
      flexDirection: 'row',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: '#FFA500',
      height: 100,
      gap: 8,
    },
    cameraButton: {
      backgroundColor: '#fff',
      borderRadius: 10,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 0.48,
      flexDirection: 'row',
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: '#4285F4',
      height: 100,
      gap: 8,
    },
    imageButtonText: {
      fontSize: 14,
      color: '#BE3E28',
      fontWeight: '500',
    },
    galleryButtonText: {
      fontSize: 14,
      color: '#FFA500',
      fontWeight: '500',
    },
    cameraButtonText: {
      fontSize: 14,
      color: '#4285F4',
      fontWeight: '500',
    },
    imagePreviewContainer: {
      marginTop: 8,
      marginBottom: 26,
    },
    imagePreviewScroll: {
      flexDirection: 'row',
    },
    imagePreview: {
      position: 'relative',
      marginRight: 12,
      alignItems: 'center',
    },
    previewImage: {
      width: 200,
      height: 200,
      borderRadius: 10,
    },
    removeImageButton: {
      position: 'absolute',
      top: 0,
      right: 30,
      backgroundColor: '#BE3E28',
      borderRadius: 12,
      width: 25,
      height: 25,
      alignItems: 'center',
      justifyContent: 'center',
    },
    submitButton: {
      backgroundColor: '#FF6B35', // Fallback color if gradient doesn't work
      borderRadius: 16, // rounded-2xl equivalent
      padding: 16, // py-4 equivalent
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      margin: 10,
      marginTop: 5,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 8, // shadow-lg equivalent
    },
    clothesButton: {
      backgroundColor: '#ef5454',
    },
    submitButtonText: {
      color: 'white',
      fontSize: 18,
      fontWeight: 'bold',
    },
    clothingItemContainer: {
      backgroundColor: '#fff',
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    clothingItemHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    clothingItemTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
    },
    MainTitle: {
      fontSize: 25,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 12,
      textAlign: 'center',
    },
    removeItemButton: {
      backgroundColor: '#BE3E28',
      borderRadius: 20,
      width: 30,
      height: 30,
      alignItems: 'center',
      flexDirection: 'row', 
      justifyContent: 'center',
    },
    addItemButton: {
      backgroundColor: '#65a765',
      borderRadius: 20,
      padding: 2,
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row', 
      marginTop: 0,
    },
    addItemButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    quantityContainer: {
      marginBottom: 16,
      marginTop: 8,
    },
    quantityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    quantityControls: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      padding: 8,
      marginLeft: 16,
      flex: 0.6,
    },
    quantityButton: {
      backgroundColor: '#E0E0E0',
      borderRadius: 4,
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quantityButtonDisabled: {
      backgroundColor: '#F0F0F0',
    },
    quantityText: {
      fontSize: 18,
      fontWeight: 'bold',
      marginHorizontal: 16,
    },
    imageSection: {
      marginBottom: 16,
    },
    imageHelpText: {
      fontSize: 14,
      color: '#777',
      marginBottom: 8,
    },
    imageButtonsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 26,
    },
    aiButton: {
      backgroundColor: '#FCF2E9',
      borderRadius: 8,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      marginBottom: 26,
      borderWidth: 1,
      borderColor: '#BE3E28',
    },
    aiButtonText: {
      color: '#BE3E28',
      fontSize: 16,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    colorInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 26,
    },
    colorInput: {
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      flex: 1,
    },
    colorPreview: {
      width: 24,
      height: 24,
      borderRadius: 4,
      marginLeft: 8,
    },
    aiPredictionsContainer: {
      flexDirection: 'column',
      alignItems: 'stretch',
      marginBottom: 26,
    },
    aiPredictionButton: {
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      padding: 12,
      marginBottom: 26,
    },
    aiPredictionButtonSelected: {
      backgroundColor: '#E0E0E0',
    },
    aiPredictionText: {
      fontSize: 16,
      color: '#333',
    },
    aiPredictionTextSelected: {
      fontWeight: 'bold',
    },
    aiColorsContainer: {
      flexDirection: 'column',
      alignItems: 'stretch',
      marginBottom: 26,
    },
    aiColorsRowContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 26,
    },
    aiColorCircleButton: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: 8,
    },
    aiColorCircle: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginBottom: 5,
      borderWidth: 1,
      borderColor: '#e0e0e0',
    },
    aiColorPercentage: {
      fontSize: 12,
      color: '#555',
      textAlign: 'center',
    },
    aiColorButton: {
      backgroundColor: '#F5F5F5',
      borderRadius: 8,
      padding: 12,
      marginBottom: 26,
      flexDirection: 'row',
      alignItems: 'center',
    },
    aiColorButtonSelected: {
      backgroundColor: '#E0E0E0',
    },
    aiColorText: {
      fontSize: 16,
      color: '#333',
      marginLeft: 8,
    },
    aiColorTextSelected: {
      fontWeight: 'bold',
    },
    applyAiButton: {
      backgroundColor: '#2D5A27',
      borderRadius: 8,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 26,
    },
    applyAiButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: 'bold',
    },
    navIcon1: {
      width: 20,
      height: 20,
    },
    navIcon: {
      width: 50,
      height: 50,
    },
    genderRadioContainer: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      marginBottom: 26,
      shadowColor: '#00000050',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    genderTitle: {
      fontWeight: 'bold',
      fontSize: 16,
      marginBottom: 26,
      textAlign: 'center',
      color: '#555',
    },
    genderOptionsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 26,
    },
    genderRadioOption: {
      alignItems: 'center',
      width: '30%',
    },
    genderRadioCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: '#ddd',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      top: -8,
      right: -8,
      zIndex: 1,
    },
    genderRadioCircleSelected: {
      borderColor: '#BE3E28',
    },
    genderRadioInnerCircle: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#BE3E28',
    },
    genderIconContainer: {
      width: 50,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    genderLabel: {
      fontSize: 12,
      color: '#555',
      textAlign: 'center',
    },
    sizeOptionsRow: {
      flexDirection: 'row',
      paddingVertical: 9,
    },
    sizeCircle: {
      width: 35,
      height: 35,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
      backgroundColor: '#e6f2ff50',
      borderWidth: 1,
      borderColor: '#e0e0e0',
    },
    sizeCircleSelected: {
      backgroundColor: '#e6f2ff',
      borderWidth: 1,
      borderColor: '#4285F4',
    },
    sizeCircleText: {
      fontSize: 10,
      fontWeight: '700',
      color: '#555',
    },
    sizeCircleTextSelected: {
      color: '#4285F4',
      fontWeight: 'bold',
    },
    colorContainer: {
      marginBottom: 9,
    },
    colorOptionsRow: {
      flexDirection: 'row',
      paddingVertical: 8,
    },
    colorCircle: {
      width: 30,
      height: 30,
      borderRadius: 15,
      marginRight: 15,
      borderWidth: 1,
      borderColor: '#e0e0e0',
    },
    colorCircleSelected: {
      borderWidth: 2,
      borderColor: '#4285F4',
    },
    aiColorContainer: {
      position: 'relative',
      marginRight: 2,
    },
    aiColorBadge: {
      position: 'absolute',
      top: -1,
      right: -1,
      backgroundColor: '#4285F4',
      borderRadius: 8,
      paddingHorizontal: 4,
      paddingVertical: 2,
    },
    aiColorBadgeText: {
      color: 'white',
      fontSize: 8,
      fontWeight: 'bold',
    },
    aiButtonContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6366F1',
      borderRadius: 16,
      padding: 16,
      marginVertical: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 8,
      position: 'relative',
    },
    aiBadge: {
      position: 'absolute',
      top: -10,
      right: -10,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#6366F1',
      borderWidth: 2,
      borderColor: '#6366F1',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 4,
    },
    aiButtonTextContainer: {
      marginLeft: 10,
    },
    aiButtonTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: 'white',
    },
    aiButtonDescription: {
      fontSize: 12,
      color: 'rgba(255, 255, 255, 0.8)',
    },
    formContainer: {
      width: '100%',
    },
    swipeIndicatorContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
    },
    buttonContainer: {
      paddingHorizontal: 16,
      paddingTop: 0,
      paddingBottom: 10,
      marginTop: 0,
    },
  });
  export default styles;
